/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#5b0c00',
        'surface-dim': '#cbd6df',
        primary: '#b22200',
        'secondary-fixed': '#d7e2ff',
        outline: '#71787d',
        'on-secondary': '#eff2ff',
        'on-primary': '#ffefec',
        'surface-variant': '#d4dee7',
        'inverse-primary': '#fe5733',
        'primary-container': '#ff785a',
        'on-error': '#ffefef',
        'on-error-container': '#510017',
        surface: '#f1f7fd',
        'surface-container': '#e1e9f1',
        'secondary-fixed-dim': '#c9d4f0',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#dae4ec',
        secondary: '#515c73',
        'on-surface': '#293034',
        tertiary: '#29664c',
        'tertiary-fixed': '#beffdc',
        'surface-bright': '#f1f7fd',
        'surface-container-low': '#eaf2f9',
        error: '#b41340',
        'surface-tint': '#b22200',
        'inverse-on-surface': '#979ea3',
        'primary-fixed': '#ff785a',
        'tertiary-container': '#beffdc',
        'on-surface-variant': '#555c62',
        'outline-variant': '#a7aeb4',
        'on-background': '#293034',
        'secondary-dim': '#455067',
        'on-secondary-fixed-variant': '#515c73',
        'error-container': '#f74b6d',
        'error-dim': '#a70138',
        'on-tertiary-fixed': '#105239',
        'tertiary-dim': '#1b5a40',
        'on-secondary-container': '#475269',
        'secondary-container': '#d7e2ff',
        'tertiary-fixed-dim': '#b1f0ce',
        'on-secondary-fixed': '#353f56',
        'on-tertiary-container': '#27654a',
        'on-primary-fixed': '#000000',
        'on-primary-container': '#4a0800',
        'on-tertiary': '#c8ffe0',
        'surface-container-highest': '#d4dee7',
        'inverse-surface': '#080f13',
        'primary-fixed-dim': '#ff5c39',
        background: '#f1f7fd',
        'primary-dim': '#9c1c00',
        'on-tertiary-fixed-variant': '#336f54',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
