/** @type {import('tailwindcss').Config} */

const THEME_COLOR_KEYS = [
  'on-primary-fixed-variant',
  'surface-dim',
  'primary',
  'secondary-fixed',
  'outline',
  'on-secondary',
  'on-primary',
  'surface-variant',
  'inverse-primary',
  'primary-container',
  'on-error',
  'on-error-container',
  'surface',
  'surface-container',
  'secondary-fixed-dim',
  'surface-container-lowest',
  'surface-container-high',
  'secondary',
  'on-surface',
  'tertiary',
  'tertiary-fixed',
  'surface-bright',
  'surface-container-low',
  'error',
  'surface-tint',
  'inverse-on-surface',
  'primary-fixed',
  'tertiary-container',
  'on-surface-variant',
  'outline-variant',
  'on-background',
  'secondary-dim',
  'on-secondary-fixed-variant',
  'error-container',
  'error-dim',
  'on-tertiary-fixed',
  'tertiary-dim',
  'on-secondary-container',
  'secondary-container',
  'tertiary-fixed-dim',
  'on-secondary-fixed',
  'on-tertiary-container',
  'on-primary-fixed',
  'on-primary-container',
  'on-tertiary',
  'surface-container-highest',
  'inverse-surface',
  'primary-fixed-dim',
  'background',
  'primary-dim',
  'on-tertiary-fixed-variant',
]

const themeColors = Object.fromEntries(
  THEME_COLOR_KEYS.map((key) => [key, `rgb(var(--color-${key}) / <alpha-value>)`]),
)

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: themeColors,
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
